version: "3.1"
services:

    webserver:
      image: nginx:latest
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./php:/usr/share/nginx/html
      ports:
          - "80:80"
      depends_on:
          - php-fpm

    php-fpm:
      image: php:7.0-fpm     
      links:
          - mariadb
      volumes:
          - ./php:/usr/share/nginx/html
      ports:
          - 9000:9000 
    mariadb:
      image: mariadb
      volumes:
          - ./sql:/docker-entrypoint-initdb.d/
      environment:
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: sncf
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - mariadb
      environment:
       PMA_HOST: mariadb
       PMA_PORT: 3306
      ports:
          - "8080:80"
